version: '3'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SB_URL=${SB_URL}
      - SB_SERVICE_KEY=${SB_SERVICE_KEY}
      - PORT=3000
    depends_on:
      - ocr
  ocr:
    build: ./ocr_service
    ports:
      - "5001:5001"
